## From refers to base image
From ubuntu

Maintainer "SAI"

#RUN Commands
RUN apt-get update
RUN apt-get install -y vim
RUN apt-get install -y python

## Print something
CMD /bin/echo "Installation completed"
